### ISSUE TITLE
Edit Documentation

### ISSUE THREAD

**Issue by ljl7123** [stephenwithav/keydroid#12]
My university technical writing course has an assignment which involves editing documentation on GitHub repositories as practice in real world settings. Edits may involve aspects like style, structure, and concision.

Existing style guidelines would be taken into account. The following is one of the resources I would be using:
https://jacobian.org/writing/technical-style/

Would anyone mind if I propose edits to documentation in this repository? It would really help me out!

**Comment by stephenwithav** [comment]
I would appreciate the help.

I'm about to push release 0.3.0, which has new docs, so please give me 15 minutes before editing.

**Comment by stephenwithav** [comment]
Everything's now in master.  I look forward to your contributions!

**Comment by ljl7123** [comment]
@stephenwithav Sounds good, thanks!
