### ISSUE TITLE
Add contributing file

### ISSUE THREAD

**Issue by ljl7123** [stephenwithav/keydroid#13]
I was thinking of adding a file for potential contributors. @stephenwithav , could you clarify the following points:
1. are first-time contributors welcome?
2. are there any files with version numbers that need to be incremented?

Thanks in advance!

**Comment by stephenwithav** [comment]
1. They are.  Good contributions are allowed from everyone.
2. No files (currently) contain version numbers.  I do tag releases with their version numbers, however.
